In [1]:
from local_datasets.data_classes import PandasData
from local_datasets.preprocessing.encoding import BertBaseUncasedEncoder
from local_datasets.preprocessing.tokenization import BertBaseUncasedTokenizer
import pandas as pd

In [2]:
article = 'Heaven’s Gatekeeper? Jesse Jackson Proclaims That Trump ‘Would Not Qualify to Get Into Jesus’ Kingdom’ Jesse Jackson thinks he s Heaven s gatekeeper The arrogant  reverend  proclaimed that President Trump might not qualify to enter Jesus  Kingdom. How dare he!Jackson made the comments at the  Ministers March for Justice :  Trump says you must be able to speak the language of English, be qualified, and have a job skill. Jesus would not qualify to come in Trump s country he would not qualify to get into Jesus  kingdom. Jackson used religion to bash Trump during the event: He quoted part of a passage from the gospel of Matthew: I was hungry, you fed me; naked, you clothed me; captive, you set me free. Jackson was referring to the fact that he believes in open borders and welcoming arms for everyone. Nice try, it s just not true that a nation can survive without borders. This is typical of the pandering reverend who s been using minorities his entire life to profit off of. He s a grifter along with Sharpton who was in attendance of course. These shysters detest Trump because they know he s the real deal and will REALLY help all Americans.'

In [26]:
example_data = pd.read_csv('../data/Recovery/recovery.csv').head()
example_data

                                             article  label
0  The Coronavirus: What Scientists Have Learned ...      1
1  Chinese Health Officials: More Die From Newly ...      1
2  Everything you need to know about the coronavi...      1
3  Novel Coronavirus Cases Confirmed To Be Spread...      0
4  Coronavirus disrupts the world: updates on the...      1

In [28]:
data = PandasData(example_data['article'], example_data['label'])
tokenized = BertBaseUncasedTokenizer().init().preprocess(data.copy())

In [5]:
tokenized.features

0    [the, corona, ##virus, :, what, scientists, ha...
1    [chinese, health, officials, :, more, die, fro...
2    [everything, you, need, to, know, about, the, ...
3    [novel, corona, ##virus, cases, confirmed, to,...
4    [corona, ##virus, disrupt, ##s, the, world, :,...
Name: article, dtype: object

In [6]:
tokenized_list = tokenized.features.tolist()
tokenized_list

[['the',
  'corona',
  '##virus',
  ':',
  'what',
  'scientists',
  'have',
  'learned',
  'so',
  'far',
  'a',
  'novel',
  'respiratory',
  'virus',
  'that',
  'originated',
  'in',
  'wu',
  '##han',
  ',',
  'china',
  ',',
  'last',
  'december',
  'has',
  'spread',
  'to',
  'six',
  'continents',
  '.',
  'hundreds',
  'of',
  'thousands',
  'have',
  'been',
  'infected',
  ',',
  'at',
  'least',
  '20',
  ',',
  '000',
  'people',
  'have',
  'died',
  'and',
  'the',
  'spread',
  'of',
  'the',
  'corona',
  '##virus',
  'was',
  'called',
  'a',
  'pan',
  '##de',
  '##mic',
  'by',
  'the',
  'world',
  'health',
  'organization',
  'in',
  'march',
  '.',
  'much',
  'remains',
  'unknown',
  'about',
  'the',
  'virus',
  ',',
  'including',
  'how',
  'many',
  'people',
  'may',
  'have',
  'very',
  'mild',
  'or',
  'as',
  '##ym',
  '##pt',
  '##oma',
  '##tic',
  'infections',
  ',',
  'and',
  'whether',
  'they',
  'can',
  'transmit',
  'the',
  'virus',
  '.',
  'the',
  'precise',
  'dimensions',
  'of',
  'the',
  'outbreak',
  'are',
  'hard',
  'to',
  'know',
  '.',
  'here',
  '’',
  's',
  'what',
  'scientists',
  'have',
  'learned',
  'so',
  'far',
  'about',
  'the',
  'virus',
  'and',
  'the',
  'outbreak',
  '.',
  'what',
  'is',
  'a',
  'corona',
  '##virus',
  '?',
  'corona',
  '##virus',
  '##es',
  'are',
  'named',
  'for',
  'the',
  'spikes',
  'that',
  'pro',
  '##tr',
  '##ude',
  'from',
  'their',
  'surfaces',
  ',',
  'resembling',
  'a',
  'crown',
  'or',
  'the',
  'sun',
  '’',
  's',
  'corona',
  '.',
  'they',
  'can',
  'in',
  '##fect',
  'both',
  'animals',
  'and',
  'people',
  ',',
  'and',
  'can',
  'cause',
  'illnesses',
  'of',
  'the',
  'respiratory',
  'tract',
  '.',
  'at',
  'least',
  'four',
  'types',
  'of',
  'corona',
  '##virus',
  '##es',
  'cause',
  'very',
  'mild',
  'infections',
  'every',
  'year',
  ',',
  'like',
  'the',
  'common',
  'cold',
  '.',
  'most',
  'people',
  'get',
  'infected',
  'with',
  'one',
  'or',
  'more',
  'of',
  'these',
  'viruses',
  'at',
  'some',
  'point',
  'in',
  'their',
  'lives',
  '.',
  'another',
  'corona',
  '##virus',
  'that',
  'circulated',
  'in',
  'china',
  'in',
  '2003',
  'caused',
  'a',
  'more',
  'dangerous',
  'condition',
  'known',
  'as',
  'severe',
  'acute',
  'respiratory',
  'syndrome',
  ',',
  'or',
  'sar',
  '##s',
  '.',
  'the',
  'virus',
  'was',
  'contained',
  'after',
  'it',
  'had',
  'sick',
  '##ened',
  '8',
  ',',
  '09',
  '##8',
  'people',
  'and',
  'killed',
  '77',
  '##4',
  '.',
  'middle',
  'east',
  'respiratory',
  'syndrome',
  ',',
  'or',
  'mer',
  '##s',
  ',',
  'first',
  'reported',
  'in',
  'saudi',
  'arabia',
  'in',
  '2012',
  ',',
  'is',
  'also',
  'caused',
  'by',
  'a',
  'corona',
  '##virus',
  '.',
  'the',
  'new',
  'virus',
  'has',
  'been',
  'named',
  'sar',
  '##s',
  '-',
  'co',
  '##v',
  '-',
  '2',
  '.',
  'the',
  'disease',
  'it',
  'causes',
  'is',
  'called',
  'co',
  '##vid',
  '-',
  '19',
  '.',
  'how',
  'dangerous',
  'is',
  'it',
  '?',
  'it',
  'is',
  'hard',
  'to',
  'accurately',
  'assess',
  'the',
  'lethal',
  '##ity',
  'of',
  'a',
  'new',
  'virus',
  '.',
  'it',
  'appears',
  'to',
  'be',
  'less',
  'often',
  'fatal',
  'than',
  'the',
  'corona',
  '##virus',
  '##es',
  'that',
  'caused',
  'sar',
  '##s',
  'or',
  'mer',
  '##s',
  ',',
  'but',
  'significantly',
  'more',
  'so',
  'than',
  'the',
  'seasonal',
  'flu',
  '.',
  'the',
  'fatal',
  '##ity',
  'rate',
  'was',
  'over',
  '2',
  'percent',
  ',',
  'in',
  'one',
  'study',
  '.',
  'but',
  'government',
  'scientists',
  'have',
  'estimated',
  'that',
  'the',
  'real',
  'figure',
  'could',
  'be',
  'below',
  '1',
  'percent',
  ',',
  'roughly',
  'the',
  'rate',
  'occurring',
  'in',
  'a',
  'severe',
  'flu',
  'season',
  '.',
  'about',
  '5',
  'percent',
  'of',
  'the',
  'patients',
  'who',
  'were',
  'hospitalized',
  'in',
  'china',
  'had',
  'critical',
  'illnesses',
  '.',
  'children',
  'seem',
  'less',
  'likely',
  'to',
  'be',
  'infected',
  'with',
  'the',
  'new',
  'corona',
  '##virus',
  ',',
  'while',
  'middle',
  '-',
  'aged',
  'and',
  'older',
  'adults',
  'are',
  'di',
  '##sp',
  '##rop',
  '##ort',
  '##ion',
  '##ately',
  'infected',
  '.',
  'men',
  'are',
  'more',
  'likely',
  'to',
  'die',
  'from',
  'an',
  'infection',
  'compared',
  'to',
  'women',
  ',',
  'possibly',
  'because',
  'they',
  'produce',
  'weaker',
  'immune',
  'responses',
  'and',
  'have',
  'higher',
  'rates',
  'of',
  'tobacco',
  'consumption',
  ',',
  'type',
  '2',
  'diabetes',
  'and',
  'high',
  'blood',
  'pressure',
  'than',
  'women',
  ',',
  'which',
  'may',
  'increase',
  'the',
  'risk',
  'of',
  'complications',
  'following',
  'an',
  'infection',
  '.',
  '“',
  'this',
  'is',
  'a',
  'pattern',
  'we',
  '’',
  've',
  'seen',
  'with',
  'many',
  'viral',
  'infections',
  'of',
  'the',
  'respiratory',
  'tract',
  '—',
  'men',
  'can',
  'have',
  'worse',
  'outcomes',
  ',',
  '”',
  'said',
  'sa',
  '##bra',
  'klein',
  ',',
  'a',
  'scientist',
  'who',
  'studies',
  'sex',
  'differences',
  'in',
  'viral',
  'infections',
  'and',
  'va',
  '##cci',
  '##nation',
  'responses',
  'at',
  'the',
  'johns',
  'hopkins',
  'bloomberg',
  'school',
  'of',
  'public',
  'health',
  '.',
  'how',
  'is',
  'the',
  'new',
  'corona',
  '##virus',
  'transmitted',
  '?',
  'experts',
  'believe',
  'that',
  'an',
  'infected',
  'animal',
  'may',
  'have',
  'first',
  'transmitted',
  'the',
  'virus',
  'to',
  'humans',
  'at',
  'a',
  'market',
  'that',
  'sold',
  'live',
  'fish',
  ',',
  'animals',
  'and',
  'birds',
  'in',
  'wu',
  '##han',
  '.',
  'the',
  'market',
  'was',
  'later',
  'shut',
  'down',
  'and',
  'di',
  '##sin',
  '##fect',
  '##ed',
  ',',
  'making',
  'it',
  'nearly',
  'impossible',
  'to',
  'investigate',
  'which',
  'animal',
  'may',
  'have',
  'been',
  'the',
  'exact',
  'origin',
  '.',
  'bats',
  'are',
  'considered',
  'a',
  'possible',
  'source',
  ',',
  'because',
  'they',
  'have',
  'evolved',
  'to',
  'coe',
  '##xi',
  '##st',
  'with',
  'many',
  'viruses',
  ',',
  'and',
  'they',
  'were',
  'found',
  'to',
  'be',
  'the',
  'starting',
  'point',
  'for',
  'sar',
  '##s',
  '.',
  'it',
  'is',
  'also',
  'possible',
  'that',
  'bats',
  'transmitted',
  'the',
  'virus',
  'to',
  'an',
  'intermediate',
  'animal',
  ',',
  'such',
  'as',
  'pang',
  '##olin',
  '##s',
  ',',
  'which',
  'are',
  'consumed',
  'as',
  'a',
  'del',
  '##ica',
  '##cy',
  'in',
  'parts',
  'of',
  'china',
  ',',
  'and',
  'may',
  'have',
  'then',
  'passed',
  'on',
  'the',
  'virus',
  'to',
  'humans',
  '.',
  'the',
  'outbreak',
  'grew',
  'because',
  'of',
  'human',
  '-',
  'to',
  '-',
  'human',
  'transmission',
  '.',
  'people',
  'infected',
  'with',
  'the',
  'virus',
  'produce',
  'tiny',
  'respiratory',
  'droplets',
  'when',
  'they',
  'breathe',
  ',',
  'talk',
  ',',
  'cough',
  'or',
  's',
  '##nee',
  '##ze',
  ',',
  'allowing',
  'the',
  'virus',
  'to',
  'travel',
  'through',
  'the',
  'air',
  '.',
  'most',
  'respiratory',
  'droplets',
  'fall',
  'to',
  'the',
  'ground',
  'within',
  'a',
  'few',
  'feet',
  '.',
  'people',
  'who',
  'are',
  'in',
  'close',
  'contact',
  'with',
  'those',
  'infected',
  ',',
  'particularly',
  'family',
  'members',
  'and',
  'health',
  'care',
  'workers',
  ',',
  'may',
  'catch',
  'the',
  'virus',
  'this',
  'way',
  '.',
  'scientists',
  'don',
  '’',
  't',
  'know',
  'how',
  'long',
  'the',
  'new',
  'corona',
  '##virus',
  'can',
  'live',
  'on',
  'surfaces',
  ',',
  'and',
  'preliminary',
  'research',
  'suggests',
  'that',
  'hot',
  'and',
  'humid',
  'environments',
  'may',
  'not',
  'slow',
  'down',
  'the',
  'pathogen',
  '’',
  's',
  'spread',
  '.',
  'warm',
  'weather',
  'does',
  'tend',
  'to',
  'inhibit',
  'influenza',
  'and',
  'mild',
  '##er',
  'corona',
  '##virus',
  '##es',
  '.',
  'infected',
  'people',
  'may',
  'be',
  'able',
  'to',
  'pass',
  'on',
  'the',
  'new',
  'corona',
  '##virus',
  'even',
  'if',
  'they',
  'have',
  'few',
  'obvious',
  'symptoms',
  ',',
  'a',
  'study',
  'in',
  'germany',
  'has',
  'found',
  '.',
  'that',
  '’',
  's',
  '“',
  'bad',
  'news',
  ',',
  '”',
  'said',
  'dr',
  '.',
  'william',
  'sc',
  '##ha',
  '##ff',
  '##ner',
  ',',
  'an',
  'expert',
  'in',
  'infectious',
  'diseases',
  'at',
  'vanderbilt',
  'university',
  'medical',
  'center',
  'in',
  'nashville',
  '.',
  'when',
  'people',
  'don',
  '’',
  't',
  'know',
  'they',
  'are',
  'infected',
  ',',
  '“',
  'they',
  '’',
  're',
  'up',
  'and',
  'about',
  ',',
  'going',
  'to',
  'work',
  'or',
  'the',
  'gym',
  'or',
  'to',
  'religious',
  'services',
  ',',
  'and',
  'breathing',
  'on',
  'or',
  'near',
  'other',
  'people',
  ',',
  '”',
  'he',
  'said',
  '.',
  'still',
  ',',
  'a',
  'report',
  'by',
  'the',
  'world',
  'health',
  'organization',
  'suggests',
  'that',
  'as',
  '##ym',
  '##pt',
  '##oma',
  '##tic',
  'cases',
  'are',
  'rare',
  '.',
  'what',
  'symptoms',
  'should',
  'i',
  'look',
  'out',
  'for',
  '?',
  'symptoms',
  'of',
  'this',
  'infection',
  'include',
  'fever',
  ',',
  'cough',
  'and',
  'difficulty',
  'breathing',
  'or',
  'short',
  '##ness',
  'of',
  'breath',
  '.',
  'the',
  'illness',
  'causes',
  'lung',
  'lesions',
  'and',
  'pneumonia',
  '.',
  'but',
  'mild',
  '##er',
  'cases',
  'may',
  'resemble',
  'the',
  'flu',
  'or',
  'a',
  'bad',
  'cold',
  ',',
  'making',
  'detection',
  'difficult',
  '.',
  'patients',
  'may',
  'exhibit',
  'other',
  'symptoms',
  ',',
  'too',
  ',',
  'such',
  'as',
  'gas',
  '##tro',
  '##int',
  '##estinal',
  'problems',
  'or',
  'dia',
  '##rr',
  '##hea',
  '.',
  'current',
  'estimates',
  'suggest',
  'that',
  'symptoms',
  ...],
 ['chinese',
  'health',
  'officials',
  ':',
  'more',
  'die',
  'from',
  'newly',
  'identified',
  'corona',
  '##virus',
  'chinese',
  'health',
  'officials',
  ':',
  'more',
  'die',
  'from',
  'newly',
  'identified',
  'corona',
  '##virus',
  'chinese',
  'health',
  'authorities',
  'held',
  'a',
  'briefing',
  'wednesday',
  'on',
  'a',
  'new',
  'corona',
  '##virus',
  'thought',
  'to',
  'have',
  'originated',
  'in',
  'wu',
  '##han',
  ',',
  'china',
  '.',
  'more',
  'than',
  '200',
  'cases',
  'have',
  'been',
  'detected',
  'globally',
  ',',
  'including',
  'one',
  'case',
  'in',
  'the',
  'u',
  '.',
  's',
  '.',
  'david',
  'greene',
  ',',
  'host',
  ':',
  'china',
  'is',
  'scrambling',
  'to',
  'contain',
  'a',
  'never',
  'before',
  'seen',
  'strain',
  'of',
  'corona',
  '##virus',
  '.',
  'at',
  'least',
  'nine',
  'people',
  'have',
  'died',
  ';',
  'at',
  'least',
  '440',
  'are',
  'infected',
  ',',
  'and',
  'that',
  'includes',
  '15',
  'medical',
  'staff',
  '##ers',
  '.',
  'it',
  'has',
  'already',
  'made',
  'its',
  'way',
  'to',
  'six',
  'countries',
  'now',
  ',',
  'including',
  'the',
  'united',
  'states',
  'after',
  'an',
  'american',
  'was',
  'diagnosed',
  'upon',
  'his',
  'return',
  'from',
  'the',
  'chinese',
  'city',
  'of',
  'wu',
  '##han',
  ',',
  'where',
  'the',
  'virus',
  'is',
  'thought',
  'to',
  'have',
  'originated',
  '.',
  'we',
  "'",
  're',
  'joined',
  'by',
  'npr',
  "'",
  's',
  'beijing',
  'correspondent',
  'emily',
  'feng',
  '.',
  'hi',
  ',',
  'emily',
  '.',
  'emily',
  'feng',
  ',',
  'by',
  '##line',
  ':',
  'hi',
  ',',
  'david',
  '.',
  'greene',
  ':',
  'so',
  'how',
  'worried',
  'is',
  'the',
  'chinese',
  'government',
  'about',
  'this',
  'right',
  'now',
  '?',
  'feng',
  ':',
  'they',
  "'",
  're',
  'pretty',
  'worried',
  ',',
  'but',
  'they',
  "'",
  're',
  'also',
  'being',
  'really',
  'careful',
  '.',
  'they',
  'don',
  "'",
  't',
  'want',
  'to',
  'cause',
  'a',
  'panic',
  ',',
  'but',
  'they',
  "'",
  're',
  'also',
  'trying',
  'to',
  'educate',
  'the',
  'public',
  'in',
  'how',
  'to',
  'protect',
  'themselves',
  '.',
  'some',
  'top',
  'chinese',
  'health',
  'official',
  'held',
  'a',
  'press',
  'conference',
  'today',
  'that',
  'npr',
  'went',
  'to',
  '.',
  'here',
  "'",
  's',
  'li',
  'bin',
  ',',
  'china',
  "'",
  's',
  'vice',
  'director',
  'of',
  'its',
  'national',
  'health',
  'commission',
  '.',
  '(',
  'sound',
  '##bit',
  '##e',
  'of',
  'press',
  'conference',
  ')',
  'li',
  'bin',
  ':',
  '(',
  'through',
  'interpreter',
  ')',
  'we',
  'have',
  'ensured',
  'management',
  'of',
  'export',
  'channels',
  'such',
  'as',
  'temperature',
  'checks',
  'at',
  'airports',
  ',',
  'train',
  'and',
  'bus',
  'stations',
  'and',
  'ports',
  '.',
  'and',
  'we',
  'will',
  'reduce',
  'as',
  'much',
  'as',
  'possible',
  'events',
  'with',
  'large',
  'congregations',
  '.',
  'feng',
  ':',
  'but',
  'the',
  'problem',
  'is',
  'that',
  'neither',
  '-',
  'none',
  'of',
  'these',
  'people',
  'still',
  'know',
  'exactly',
  'what',
  'caused',
  'the',
  'virus',
  '.',
  'they',
  'think',
  'it',
  'came',
  'from',
  'this',
  'open',
  '-',
  'air',
  'market',
  'where',
  'wild',
  'animals',
  'were',
  'sold',
  'and',
  'eaten',
  '.',
  'but',
  'they',
  'don',
  "'",
  't',
  'know',
  'what',
  'type',
  'of',
  'animal',
  "'",
  's',
  'behind',
  'the',
  'virus',
  ',',
  'so',
  'that',
  'makes',
  'it',
  'really',
  'hard',
  'to',
  'prevent',
  'future',
  'outbreak',
  '##s',
  '.',
  'greene',
  ':',
  'and',
  'now',
  ',',
  'i',
  'mean',
  ',',
  'this',
  'has',
  'arrived',
  'in',
  'the',
  'united',
  'states',
  '.',
  'it',
  "'",
  's',
  'arrived',
  'in',
  'other',
  'countries',
  ',',
  'which',
  'is',
  'beginning',
  'to',
  'raise',
  'more',
  'alarms',
  'around',
  'the',
  'world',
  '.',
  'i',
  'mean',
  ',',
  'can',
  'you',
  'just',
  'remind',
  'me',
  'of',
  'the',
  'timeline',
  'of',
  'all',
  'this',
  '?',
  'it',
  'seems',
  'to',
  'have',
  'almost',
  'come',
  'out',
  'of',
  'nowhere',
  '.',
  'feng',
  ':',
  'it',
  "'",
  's',
  'really',
  'exploded',
  'over',
  'the',
  'last',
  'couple',
  'of',
  'days',
  ',',
  'and',
  'there',
  'are',
  'several',
  'theories',
  'as',
  'to',
  'why',
  '.',
  'but',
  'the',
  'first',
  'case',
  'was',
  'reported',
  'about',
  '3',
  '1',
  '/',
  '2',
  'weeks',
  'ago',
  'on',
  'new',
  'year',
  "'",
  's',
  'eve',
  '.',
  'and',
  'then',
  'the',
  'cases',
  'climbed',
  ',',
  'but',
  'they',
  'plateau',
  '##ed',
  'for',
  'about',
  'three',
  'weeks',
  'and',
  'stayed',
  '-',
  'and',
  'never',
  'broke',
  ',',
  'about',
  '60',
  'confirmed',
  'cases',
  '.',
  'it',
  "'",
  's',
  'really',
  'only',
  'been',
  'in',
  'the',
  'last',
  'three',
  'days',
  'that',
  'we',
  "'",
  've',
  'this',
  'sudden',
  'jump',
  'in',
  'the',
  'number',
  'of',
  'cases',
  'in',
  'china',
  ',',
  'and',
  'you',
  "'",
  've',
  'also',
  'seen',
  'this',
  'jump',
  'in',
  'measures',
  'that',
  'authorities',
  'have',
  'taken',
  'to',
  'screen',
  'for',
  'the',
  'virus',
  'and',
  'to',
  'prevent',
  'it',
  'from',
  'spreading',
  '.',
  'so',
  'as',
  'li',
  'bin',
  'mentioned',
  ',',
  'there',
  'are',
  'now',
  'temperature',
  'sensors',
  'set',
  'up',
  'at',
  'train',
  'stations',
  'and',
  'on',
  'airplanes',
  '.',
  'they',
  "'",
  're',
  'even',
  'doing',
  'temperature',
  'checks',
  'at',
  'some',
  'hotels',
  '.',
  'but',
  'people',
  'are',
  'understand',
  '##ably',
  'very',
  ',',
  'very',
  'worried',
  '.',
  'greene',
  ':',
  'do',
  'they',
  'feel',
  'like',
  'their',
  'government',
  'is',
  'doing',
  'enough',
  'in',
  'china',
  '?',
  'feng',
  ':',
  'there',
  "'",
  's',
  'a',
  'lot',
  'of',
  'debate',
  'online',
  'about',
  'this',
  '.',
  'there',
  "'",
  's',
  'skepticism',
  'that',
  'they',
  "'",
  're',
  'even',
  'being',
  'told',
  'how',
  'severe',
  'the',
  'problem',
  'is',
  '.',
  'as',
  'of',
  'today',
  ',',
  'there',
  'are',
  'more',
  'than',
  '450',
  'confirmed',
  'cases',
  ',',
  'but',
  'that',
  "'",
  's',
  'a',
  'huge',
  'jump',
  'just',
  'in',
  'the',
  'last',
  'four',
  'days',
  'from',
  'the',
  'low',
  'numbers',
  'that',
  'were',
  'reported',
  'over',
  'the',
  'last',
  'few',
  'weeks',
  '.',
  'a',
  'london',
  'study',
  'from',
  'imperial',
  'college',
  'there',
  'has',
  'gone',
  'viral',
  'in',
  'china',
  ',',
  'and',
  'that',
  'estimates',
  'that',
  'there',
  'should',
  'be',
  'at',
  'least',
  '1',
  ',',
  '700',
  'cases',
  'based',
  'on',
  'similar',
  'types',
  'of',
  'viruses',
  'that',
  'have',
  'broken',
  'out',
  'before',
  '.',
  'china',
  'ref',
  '##ute',
  '##s',
  'that',
  'study',
  '.',
  'here',
  "'",
  's',
  'the',
  'director',
  'of',
  'china',
  "'",
  's',
  'disease',
  'control',
  'center',
  ',',
  'gao',
  'fu',
  ',',
  'today',
  'responding',
  'to',
  'the',
  'study',
  '.',
  '(',
  'sound',
  '##bit',
  '##e',
  'of',
  'archived',
  'recording',
  ')',
  'gao',
  'fu',
  ':',
  '(',
  'through',
  'interpreter',
  ')',
  'this',
  'is',
  'a',
  'mathematical',
  'model',
  '.',
  'the',
  'number',
  'you',
  'are',
  'referring',
  'to',
  'was',
  'the',
  'maximum',
  'in',
  'the',
  'range',
  'predicted',
  '.',
  'faced',
  'with',
  'viruses',
  'like',
  'this',
  ',',
  'facts',
  'must',
  'be',
  'facts',
  ',',
  'and',
  'theories',
  'are',
  'just',
  'theories',
  '.',
  'feng',
  ':',
  'so',
  'they',
  "'",
  've',
  'been',
  'really',
  ',',
  'really',
  'strict',
  'in',
  'controlling',
  'information',
  'about',
  'the',
  'virus',
  '.',
  'they',
  "'",
  've',
  'actually',
  'even',
  'detained',
  'some',
  'people',
  'who',
  'they',
  'said',
  'were',
  'spreading',
  'rumors',
  'on',
  'social',
  'media',
  ',',
  'when',
  'these',
  'people',
  'claimed',
  'that',
  'they',
  'had',
  'relatives',
  'who',
  "'",
  've',
  'gotten',
  'sick',
  'or',
  'even',
  'died',
  'and',
  'were',
  'not',
  'reported',
  'in',
  'the',
  'official',
  'statistics',
  '.',
  'but',
  'they',
  'have',
  'a',
  'reason',
  'for',
  'being',
  'suspicious',
  '.',
  'china',
  "'",
  's',
  'government',
  'does',
  'have',
  'a',
  'history',
  'of',
  'deliberately',
  'under',
  '##re',
  '##port',
  '##ing',
  'outbreak',
  '##s',
  '.',
  'the',
  'most',
  'recent',
  'example',
  'is',
  'just',
  'last',
  'year',
  '.',
  'there',
  'was',
  'something',
  'called',
  'african',
  'sw',
  '##ine',
  'flu',
  '.',
  'provincial',
  'authorities',
  'denied',
  'that',
  'the',
  'case',
  'was',
  'really',
  'severe',
  ',',
  'and',
  'that',
  'let',
  'the',
  'flu',
  'spread',
  'to',
  'other',
  'pig',
  'farms',
  'and',
  'wiped',
  'out',
  'something',
  'like',
  '40',
  '%',
  'of',
  'the',
  'pigs',
  'in',
  'china',
  '.',
  'and',
  'then',
  'most',
  'infamous',
  '##ly',
  ',',
  'in',
  '2003',
  ',',
  'sar',
  '##s',
  ',',
  'which',
  'ended',
  'up',
  'killing',
  'more',
  'than',
  '800',
  'people',
  ',',
  'but',
  'the',
  'chinese',
  'government',
  'denied',
  '.',
  'greene',
  ':',
  'npr',
  "'",
  's',
  'emily',
  'feng',
  'reporting',
  'on',
  'this',
  'virus',
  'outbreak',
  'in',
  'china',
  '.',
  'she',
  'joins',
  'us',

In [7]:
encoder = BertBaseUncasedEncoder().init()

In [8]:
tokenized_index=tokenized.features.index

In [9]:
encodings = encoder.tokenizer(tokenized_list,
                                        is_split_into_words=True,
                                        padding=True,
                                        truncation=True,
                                        max_length=512)
encodings

{'input_ids': [[101, 1103, 1884, 15789, 108, 108, 7942, 131, 1184, 6479, 1138, 3560, 1177, 1677, 170, 2281, 19192, 7942, 1115, 7506, 1107, 192, 1358, 108, 108, 5871, 1179, 117, 5144, 1161, 117, 1314, 1260, 2093, 10615, 1144, 2819, 1106, 1565, 21876, 119, 5229, 1104, 4674, 1138, 1151, 10594, 117, 1120, 1655, 1406, 117, 1288, 1234, 1138, 1452, 1105, 1103, 2819, 1104, 1103, 1884, 15789, 108, 108, 7942, 1108, 1270, 170, 13316, 108, 108, 1260, 108, 108, 1940, 1665, 1118, 1103, 1362, 2332, 2369, 1107, 8943, 119, 1277, 2606, 3655, 1164, 1103, 7942, 117, 1259, 1293, 1242, 1234, 1336, 1138, 1304, 10496, 1137, 1112, 108, 108, 194, 1306, 108, 108, 185, 1204, 108, 108, 184, 1918, 108, 108, 189, 1596, 16565, 117, 1105, 2480, 1152, 1169, 21994, 1103, 7942, 119, 1103, 10515, 10082, 1104, 1103, 8010, 1132, 1662, 1106, 1221, 119, 1303, 787, 188, 1184, 6479, 1138, 3560, 1177, 1677, 1164, 1103, 7942, 1105, 1103, 8010, 119, 1184, 1110, 170, 1884, 15789, 108, 108, 7942, 136, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1132, 1417, 1111, 1103, 23030, 1115, 5250, 108, 108, 189, 1197, 108, 108, 190, 2007, 1121, 1147, 9902, 117, 16562, 170, 6371, 1137, 1103, 3336, 787, 188, 1884, 15789, 119, 1152, 1169, 1107, 108, 108, 175, 10294, 1204, 1241, 3551, 1105, 1234, 117, 1105, 1169, 2612, 6946, 1279, 1104, 1103, 19192, 14441, 119, 1120, 1655, 1300, 3322, 1104, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 2612, 1304, 10496, 16565, 1451, 1214, 117, 1176, 1103, 1887, 2504, 119, 1211, 1234, 1243, 10594, 1114, 1141, 1137, 1167, 1104, 1292, 20942, 1120, 1199, 1553, 1107, 1147, 2491, 119, 1330, 1884, 15789, 108, 108, 7942, 1115, 18921, 1107, 5144, 1161, 1107, 1581, 2416, 170, 1167, 4249, 3879, 1227, 1112, 5199, 12104, 19192, 9318, 117, 1137, 21718, 1197, 108, 108, 188, 119, 1103, 7942, 1108, 4049, 1170, 1122, 1125, 4809, 108, 108, 4035, 1174, 129, 117, 4925, 108, 108, 129, 1234, 1105, 1841, 5581, 108, 108, 125, 119, 2243, 1746, 19192, 9318, 117, 1137, 1143, 1197, 108, 108, 188, 117, 1148, 2103, 1107, 21718, 17294, 170, 17952, 1465, 1107, 1368, 117, 1110, 1145, 2416, 1118, 170, 1884, 15789, 108, 108, 7942, 119, 1103, 1207, 7942, 1144, 1151, 1417, 21718, 1197, 108, 108, 188, 118, 1884, 108, 108, 191, 118, 123, 119, 1103, 3653, 1122, 4680, 1110, 1270, 1884, 108, 108, 191, 2386, 118, 1627, 119, 1293, 4249, 1110, 1122, 136, 1122, 1110, 1662, 1106, 14702, 15187, 1103, 14969, 108, 108, 1122, 1183, 1104, 170, 1207, 7942, 119, 1122, 2691, 1106, 1129, 1750, 1510, 11874, 1190, 1103, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1115, 2416, 21718, 1197, 108, 108, 188, 1137, 1143, 1197, 108, 108, 188, 117, 1133, 5409, 1167, 1177, 1190, 1103, 13286, 23896, 119, 1103, 11874, 108, 108, 1122, 1183, 2603, 1108, 1166, 123, 3029, 117, 1107, 1141, 2025, 119, 1133, 1433, 6479, 1138, 3555, 1115, 1103, 1842, 2482, 1180, 1129, 2071, 122, 3029, 117, 4986, 1103, 2603, 9939, 1107, 170, 5199, 23896, 1265, 119, 1164, 126, 3029, 1104, 1103, 4420, 1150, 1127, 2704, 2200, 1107, 5144, 1161, 1125, 3607, 102], [101, 5144, 6420, 2332, 3878, 131, 1167, 2939, 1121, 3599, 3626, 1884, 15789, 108, 108, 7942, 5144, 6420, 2332, 3878, 131, 1167, 2939, 1121, 3599, 3626, 1884, 15789, 108, 108, 7942, 5144, 6420, 2332, 3912, 1316, 170, 4094, 1158, 26055, 3965, 6194, 1113, 170, 1207, 1884, 15789, 108, 108, 7942, 1354, 1106, 1138, 7506, 1107, 192, 1358, 108, 108, 5871, 1179, 117, 5144, 1161, 119, 1167, 1190, 2363, 2740, 1138, 1151, 11168, 18526, 117, 1259, 1141, 1692, 1107, 1103, 190, 119, 188, 119, 5358, 18312, 2448, 1162, 117, 2989, 131, 5144, 1161, 1110, 188, 1665, 4515, 6647, 1106, 4651, 170, 1309, 1196, 1562, 10512, 1104, 1884, 15789, 108, 108, 7942, 119, 1120, 1655, 2551, 1234, 1138, 1452, 132, 1120, 1655, 18629, 1132, 10594, 117, 1105, 1115, 2075, 1405, 2657, 2546, 108, 108, 14044, 1116, 119, 1122, 1144, 1640, 1189, 1157, 1236, 1106, 1565, 2182, 1208, 117, 1259, 1103, 10280, 2231, 1170, 1126, 1821, 26237, 1389, 1108, 11534, 1852, 1117, 1862, 1121, 1103, 5144, 6420, 1331, 1104, 192, 1358, 108, 108, 5871, 1179, 117, 1187, 1103, 7942, 1110, 1354, 1106, 1138, 7506, 119, 1195, 112, 1231, 1688, 1118, 183, 1643, 1197, 112, 188, 1129, 23784, 2118, 12499, 9712, 5264, 175, 14429, 119, 20844, 117, 9712, 5264, 119, 9712, 5264, 175, 14429, 117, 1118, 108, 108, 1413, 131, 20844, 117, 5358, 18312, 119, 2448, 1162, 131, 1177, 1293, 4472, 1110, 1103, 5144, 6420, 1433, 1164, 1142, 1268, 1208, 136, 175, 14429, 131, 1152, 112, 1231, 2785, 4472, 117, 1133, 1152, 112, 1231, 1145, 1217, 1541, 5784, 119, 1152, 1274, 112, 189, 1328, 1106, 2612, 170, 7011, 117, 1133, 1152, 112, 1231, 1145, 1774, 1106, 18584, 1103, 1470, 1107, 1293, 1106, 3244, 2310, 119, 1199, 1499, 5144, 6420, 2332, 2078, 1316, 170, 3181, 3511, 2052, 1115, 183, 1643, 1197, 1355, 1106, 119, 1303, 112, 188, 181, 1182, 9055, 117, 5144, 1161, 112, 188, 4711, 1900, 1104, 1157, 1569, 2332, 5500, 119, 113, 1839, 108, 108, 2113, 108, 108, 174, 1104, 3181, 3511, 114, 181, 1182, 9055, 131, 113, 1194, 23102, 114, 1195, 1138, 17349, 2635, 1104, 10107, 6412, 1216, 1112, 4143, 15008, 1120, 15797, 117, 2669, 1105, 3592, 2930, 1105, 9267, 119, 1105, 1195, 1209, 4851, 1112, 1277, 1112, 1936, 1958, 1114, 1415, 19215, 119, 175, 14429, 131, 1133, 1103, 2463, 1110, 1115, 4534, 118, 3839, 1104, 1292, 1234, 1253, 1221, 2839, 1184, 2416, 1103, 7942, 119, 1152, 1341, 1122, 1338, 1121, 1142, 1501, 118, 1586, 2319, 1187, 4098, 3551, 1127, 1962, 1105, 8527, 119, 1133, 1152, 1274, 112, 189, 1221, 1184, 2076, 1104, 3724, 112, 188, 1481, 1103, 7942, 117, 1177, 1115, 2228, 1122, 1541, 1662, 1106, 3843, 2174, 8010, 108, 108, 188, 119, 2448, 1162, 131, 1105, 1208, 117, 178, 1928, 117, 1142, 1144, 2474, 1107, 1103, 10280, 2231, 119, 1122, 112, 188, 2474, 1107, 1168, 2182, 117, 1134, 1110, 2150, 1106, 4693, 1167, 8819, 1116, 1213, 1103, 1362, 119, 178, 1928, 117, 1169, 1128, 1198, 11484, 1143, 1104, 1103, 21169, 1104, 1155, 1142, 136, 1122, 3093, 1106, 1138, 1593, 1435, 1149, 1104, 8251, 119, 175, 14429, 131, 1122, 112, 188, 1541, 102], [101, 1917, 1128, 1444, 1106, 1221, 1164, 1103, 1884, 15789, 108, 108, 7942, 1470, 2332, 8724, 1213, 1103, 12868, 1132, 188, 1665, 4515, 6647, 1106, 2437, 117, 1854, 117, 1105, 4651, 170, 1207, 7942, 1115, 1691, 1107, 192, 1358, 108, 108, 5871, 1179, 117, 5144, 1161, 117, 1120, 1103, 2150, 1104, 1260, 2093, 10615, 10351, 119, 1103, 1362, 2332, 2369, 113, 1150, 114, 1417, 1103, 3653, 2416, 1118, 1103, 7942, 1884, 108, 108, 191, 2386, 118, 1627, 117, 1134, 7732, 1103, 2076, 1104, 7942, 1105, 1103, 1214, 1122, 5338, 119, 1103, 1150, 3332, 1115, 1103, 7942, 1110, 170, 13316, 108, 108, 1260, 108, 108, 1940, 1665, 119, 1103, 18691, 1110, 4857, 1146, 108, 108, 4676, 1142, 3674, 1114, 1155, 1103, 6270, 2371, 1105, 3622, 119, 1128, 1169, 1267, 1187, 1105, 1293, 1242, 2740, 1104, 1103, 6946, 1138, 1151, 2103, 1107, 1142, 4520, 119, 1103, 2656, 1104, 1103, 6946, 1279, 1127, 2786, 1107, 5144, 1161, 117, 1187, 1103, 7942, 1148, 5338, 117, 1133, 1103, 2603, 1104, 1207, 2740, 1175, 1144, 2212, 2141, 119, 1175, 1132, 1208, 1242, 1551, 1167, 2740, 1796, 1104, 5144, 1161, 1190, 1175, 1127, 1656, 1104, 1122, 1120, 1103, 3976, 1104, 1103, 8010, 119, 1175, 1132, 1415, 8010, 108, 108, 188, 1104, 1103, 3653, 1107, 2967, 2844, 117, 1259, 22620, 1394, 117, 1122, 17449, 117, 1105, 1103, 10280, 2231, 117, 1134, 1971, 1144, 1103, 4997, 8010, 1104, 1251, 1583, 1107, 1103, 1362, 119, 1112, 1142, 1696, 1642, 3430, 1106, 8362, 108, 108, 11203, 117, 1412, 2810, 1110, 1106, 2590, 1155, 1104, 1240, 3243, 1112, 1234, 1250, 1106, 2437, 1142, 7942, 1105, 4651, 1157, 2819, 119, 1952, 1104, 8792, 1187, 1225, 1103, 7942, 1435, 1121, 136, 1120, 1103, 1322, 1104, 1260, 2093, 10615, 117, 1470, 2332, 3878, 1121, 5144, 1161, 6189, 1103, 1362, 2332, 2369, 1115, 1152, 1125, 170, 2463, 131, 1126, 3655, 117, 1207, 7942, 1108, 3989, 20673, 118, 1176, 6946, 1107, 1103, 1331, 1104, 192, 1358, 108, 108, 5871, 1179, 119, 1152, 1976, 3552, 1115, 1122, 1108, 170, 1884, 15789, 108, 108, 7942, 1105, 1115, 1122, 1108, 5223, 9243, 1194, 1105, 1796, 1104, 192, 1358, 108, 108, 5871, 1179, 119, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1132, 1887, 1107, 3551, 1104, 1155, 7553, 117, 1105, 1152, 2121, 1169, 23530, 1154, 2769, 1115, 1169, 1107, 108, 108, 175, 10294, 1204, 3612, 119, 1290, 1103, 1838, 1104, 1103, 1432, 117, 1160, 1168, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1138, 4874, 1106, 3612, 117, 3989, 1103, 21718, 1197, 108, 108, 188, 8010, 1107, 1617, 1105, 1103, 1143, 1197, 108, 108, 188, 8010, 1107, 1368, 119, 6479, 1341, 1142, 1207, 7942, 1148, 1245, 4451, 1104, 8987, 1106, 3612, 1120, 1103, 2150, 1104, 1260, 2093, 10615, 119, 1122, 2034, 1882, 1176, 1103, 7942, 1148, 10594, 1234, 1120, 170, 2343, 24263, 2319, 1107, 192, 1358, 108, 108, 5871, 1179, 1105, 2819, 1121, 1175, 119, 1133, 1141, 3622, 1104, 1346, 2740, 1104, 1103, 6946, 117, 1502, 1113, 179, 19762, 3113, 13722, 117, 1276, 1115, 1103, 1148, 5351, 1106, 1243, 4809, 1225, 1136, 1138, 1251, 3232, 1114, 1103, 2319, 119, 8724, 1132, 102], [101, 2281, 1884, 15789, 108, 108, 7942, 2740, 3659, 1106, 1129, 9243, 1103, 1148, 1160, 1884, 15789, 108, 108, 7942, 2740, 1107, 27772, 3186, 1138, 1151, 11168, 1107, 175, 10555, 117, 1105, 170, 1248, 1692, 1144, 1151, 3659, 1107, 1821, 26237, 1161, 1112, 5144, 1161, 27903, 1157, 3268, 1106, 1654, 1157, 8010, 119, 3201, 8214, 108, 108, 188, 1138, 1151, 1508, 1107, 1282, 1105, 2925, 1121, 2129, 5144, 1161, 1106, 5877, 1508, 17265, 1104, 9215, 1104, 1234, 1107, 1469, 5842, 108, 108, 1205, 119, 1103, 7942, 1108, 1148, 11168, 1107, 192, 1358, 108, 108, 5871, 1179, 1187, 3239, 1132, 3915, 1106, 3076, 170, 4032, 1908, 2704, 1106, 7299, 4420, 4634, 1118, 1103, 3653, 119, 1155, 1213, 5144, 1161, 117, 1259, 1107, 1103, 2364, 1129, 23784, 2118, 3912, 1132, 19722, 108, 108, 181, 1158, 1155, 3550, 4652, 1116, 1105, 7731, 1115, 1156, 12910, 1103, 3450, 3782, 1106, 3644, 1515, 1415, 1470, 7410, 1134, 1156, 2561, 1103, 3264, 12671, 1111, 1103, 17341, 7942, 1106, 2819, 1748, 119, 1167, 1190, 6032, 108, 108, 121, 2740, 1104, 1884, 15789, 108, 108, 7942, 8974, 1138, 1151, 3659, 117, 1120, 1655, 1744, 1234, 1138, 1452, 117, 1105, 1330, 129, 117, 18650, 1234, 1132, 2103, 1118, 1129, 1223, 186, 1358, 108, 108, 170, 4047, 108, 108, 14086, 1162, 1105, 8310, 1111, 1936, 8974, 1170, 170, 10005, 1104, 20673, 2740, 1127, 2103, 1121, 1234, 1150, 2323, 170, 2343, 24263, 2319, 1107, 192, 1358, 108, 108, 5871, 1179, 1113, 1260, 1665, 119, 1955, 119, 10351, 117, 1995, 1552, 1224, 1103, 1554, 176, 1424, 108, 108, 184, 7257, 4954, 1104, 7942, 1108, 1189, 1470, 119, 170, 1685, 8071, 1299, 1121, 192, 1358, 108, 108, 5871, 1179, 1144, 1452, 5920, 5365, 4423, 1103, 17638, 108, 108, 188, 1116, 1104, 1103, 7942, 1112, 1146, 1235, 1173, 1103, 6047, 2656, 1104, 5256, 1138, 1151, 1166, 1103, 1425, 1104, 2539, 1114, 3073, 108, 108, 4252, 108, 108, 1110, 1204, 108, 108, 16664, 2975, 119, 170, 5842, 108, 108, 1205, 1110, 1217, 17538, 1506, 1415, 2192, 1104, 1103, 3199, 1104, 10960, 108, 108, 174, 1182, 12759, 1166, 2588, 1550, 3555, 1234, 119, 1103, 5144, 6420, 2657, 1449, 1110, 7851, 1106, 16743, 1114, 1103, 8010, 1112, 1562, 1107, 1103, 3756, 1104, 1166, 108, 108, 25586, 108, 108, 1260, 1181, 8894, 117, 13713, 2657, 3239, 117, 1105, 173, 108, 108, 3223, 108, 108, 181, 1158, 5508, 119, 1160, 2740, 1138, 1208, 1151, 3659, 1107, 175, 10555, 1118, 1103, 175, 18129, 2332, 3907, 117, 1141, 1217, 1107, 1103, 1331, 1104, 171, 6944, 8221, 1775, 1105, 1103, 1168, 1107, 14247, 1548, 117, 1241, 4420, 1127, 3055, 1107, 5144, 1161, 1105, 3912, 8095, 1115, 1167, 2740, 1209, 2620, 12982, 119, 1175, 1132, 5365, 1115, 1234, 1336, 1129, 14255, 108, 108, 9235, 108, 108, 178, 2285, 1114, 1103, 7942, 1256, 1196, 25988, 8006, 117, 1105, 7011, 1144, 2819, 1373, 1114, 1103, 3653, 1114, 1211, 9535, 1217, 1359, 1113, 7597, 1137, 1940, 1116, 108, 108, 1107, 108, 108, 1532, 108, 108, 1120, 1988, 1543, 1103, 2187, 4146, 119, 1443, 2330, 15549, 1909, 1121, 2078, 3509, 117, 12287, 1105, 1940, 1116, 108, 108, 1107, 102], [101, 1884, 15789, 108, 108, 7942, 26499, 108, 108, 188, 1103, 1362, 131, 15549, 1113, 1103, 13316, 108, 108, 1260, 108, 108, 1940, 1665, 170, 1207, 1884, 15789, 108, 108, 7942, 1691, 1107, 192, 1358, 108, 108, 5871, 1179, 117, 5144, 1161, 117, 1120, 1103, 1838, 1104, 1260, 2093, 10615, 117, 1105, 1122, 1144, 1290, 10594, 9215, 1104, 1234, 1155, 1166, 1103, 1362, 119, 1107, 8943, 117, 1103, 1362, 2332, 2369, 3332, 1115, 1103, 7942, 1108, 170, 13316, 108, 108, 1260, 108, 108, 1940, 1665, 119, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1132, 1887, 1107, 1242, 3322, 1104, 3551, 1105, 1169, 2121, 5152, 1106, 3612, 119, 1107, 1142, 1692, 117, 1103, 7942, 1930, 2034, 1338, 1121, 170, 7693, 119, 1160, 1168, 1884, 15789, 108, 108, 7942, 108, 108, 13936, 1138, 10594, 3612, 117, 3989, 8010, 108, 108, 188, 1104, 21718, 1197, 108, 108, 188, 1105, 1143, 1197, 108, 108, 188, 1107, 1617, 1105, 1368, 117, 3569, 119, 1103, 6946, 2416, 1118, 1103, 1207, 1884, 15789, 108, 108, 7942, 117, 1884, 108, 108, 191, 2386, 118, 1627, 117, 2691, 1106, 2612, 10880, 117, 21810, 117, 1105, 7262, 4943, 119, 1168, 8006, 1511, 2445, 1104, 5080, 1105, 4773, 1105, 3245, 108, 108, 189, 2180, 108, 108, 1107, 1204, 108, 108, 12890, 14196, 2645, 119, 1199, 1234, 1309, 3934, 8006, 1133, 1180, 1253, 1107, 108, 108, 175, 10294, 1204, 1639, 119, 1103, 6946, 2691, 1106, 1129, 5199, 1107, 1213, 170, 3861, 1104, 1884, 108, 108, 191, 2386, 118, 1627, 4420, 117, 1105, 4674, 1104, 1234, 1138, 1452, 1121, 1103, 3653, 1107, 1103, 1366, 1105, 1213, 1103, 1362, 119, 1470, 2332, 3878, 1132, 1253, 1774, 1106, 1654, 21348, 8010, 108, 108, 188, 1107, 1242, 2182, 117, 1105, 6479, 1132, 6205, 1111, 14115, 119, 1112, 1115, 1250, 3430, 117, 5028, 1132, 3210, 2083, 108, 108, 5048, 117, 8894, 1132, 7851, 117, 1105, 9215, 1104, 1234, 1132, 6218, 186, 1358, 108, 108, 170, 4047, 108, 108, 14086, 1162, 108, 108, 173, 1111, 1147, 3429, 1105, 1103, 3429, 1104, 1639, 119, 2812, 1155, 1104, 1103, 15549, 1113, 1142, 23657, 1642, 1303, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [10]:
df_feature_encodings = pd.DataFrame(data=encodings.data, index=tokenized_index)
df_feature_encodings

,input_ids,token_type_ids,attention_mask
0,"[101, 1103, 1884, 15789, 108, 108, 7942, 131, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"[101, 5144, 6420, 2332, 3878, 131, 1167, 2939,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,"[101, 1917, 1128, 1444, 1106, 1221, 1164, 1103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,"[101, 2281, 1884, 15789, 108, 108, 7942, 2740,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,"[101, 1884, 15789, 108, 108, 7942, 26499, 108,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [11]:
tokenized.features = df_feature_encodings

In [13]:
tokenized.features

,input_ids,token_type_ids,attention_mask
0,"[101, 1103, 1884, 15789, 108, 108, 7942, 131, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"[101, 5144, 6420, 2332, 3878, 131, 1167, 2939,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,"[101, 1917, 1128, 1444, 1106, 1221, 1164, 1103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,"[101, 2281, 1884, 15789, 108, 108, 7942, 2740,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,"[101, 1884, 15789, 108, 108, 7942, 26499, 108,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [31]:
# tokenized = BertBaseUncasedTokenizer().init().preprocess(data)
encoder.preprocess(tokenized.copy()).dataset

,input_ids,token_type_ids,attention_mask,label
0,"[101, 1103, 1884, 15789, 108, 108, 7942, 131, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
1,"[101, 5144, 6420, 2332, 3878, 131, 1167, 2939,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
2,"[101, 1917, 1128, 1444, 1106, 1221, 1164, 1103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
3,"[101, 2281, 1884, 15789, 108, 108, 7942, 2740,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0
4,"[101, 1884, 15789, 108, 108, 7942, 26499, 108,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1