In [67]:
import pandas as pd
from transformers import BertTokenizer
import datasets as hf_datasets

random_state = 42

In [29]:
article = 'Heaven’s Gatekeeper? Jesse Jackson Proclaims That Trump ‘Would Not Qualify to Get Into Jesus’ Kingdom’ Jesse Jackson thinks he s Heaven s gatekeeper The arrogant  reverend  proclaimed that President Trump might not qualify to enter Jesus  Kingdom. How dare he!Jackson made the comments at the  Ministers March for Justice :  Trump says you must be able to speak the language of English, be qualified, and have a job skill. Jesus would not qualify to come in Trump s country he would not qualify to get into Jesus  kingdom. Jackson used religion to bash Trump during the event: He quoted part of a passage from the gospel of Matthew: I was hungry, you fed me; naked, you clothed me; captive, you set me free. Jackson was referring to the fact that he believes in open borders and welcoming arms for everyone. Nice try, it s just not true that a nation can survive without borders. This is typical of the pandering reverend who s been using minorities his entire life to profit off of. He s a grifter along with Sharpton who was in attendance of course. These shysters detest Trump because they know he s the real deal and will REALLY help all Americans.'

sentence = 'Belarus leader, Alexander Lukashenko, met Putin on Monday in Sochi.'

In [3]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [28]:
tokenized = tokenizer.tokenize(article)
print(len(tokenized))
print(tokenized)

242
['heaven', '’', 's', 'gate', '##keeper', '?', 'jesse', 'jackson', 'pro', '##claim', '##s', 'that', 'trump', '‘', 'would', 'not', 'qualify', 'to', 'get', 'into', 'jesus', '’', 'kingdom', '’', 'jesse', 'jackson', 'thinks', 'he', 's', 'heaven', 's', 'gate', '##keeper', 'the', 'arrogant', 'reverend', 'proclaimed', 'that', 'president', 'trump', 'might', 'not', 'qualify', 'to', 'enter', 'jesus', 'kingdom', '.', 'how', 'dare', 'he', '!', 'jackson', 'made', 'the', 'comments', 'at', 'the', 'ministers', 'march', 'for', 'justice', ':', 'trump', 'says', 'you', 'must', 'be', 'able', 'to', 'speak', 'the', 'language', 'of', 'english', ',', 'be', 'qualified', ',', 'and', 'have', 'a', 'job', 'skill', '.', 'jesus', 'would', 'not', 'qualify', 'to', 'come', 'in', 'trump', 's', 'country', 'he', 'would', 'not', 'qualify', 'to', 'get', 'into', 'jesus', 'kingdom', '.', 'jackson', 'used', 'religion', 'to', 'bash', 'trump', 'during', 'the', 'event', ':', 'he', 'quoted', 'part', 'of', 'a', 'passage', 'from', 'the', 'gospel', 'of', 'matthew', ':', 'i', 'was', 'hungry', ',', 'you', 'fed', 'me', ';', 'naked', ',', 'you', 'clothed', 'me', ';', 'captive', ',', 'you', 'set', 'me', 'free', '.', 'jackson', 'was', 'referring', 'to', 'the', 'fact', 'that', 'he', 'believes', 'in', 'open', 'borders', 'and', 'welcoming', 'arms', 'for', 'everyone', '.', 'nice', 'try', ',', 'it', 's', 'just', 'not', 'true', 'that', 'a', 'nation', 'can', 'survive', 'without', 'borders', '.', 'this', 'is', 'typical', 'of', 'the', 'pan', '##der', '##ing', 'reverend', 'who', 's', 'been', 'using', 'minorities', 'his', 'entire', 'life', 'to', 'profit', 'off', 'of', '.', 'he', 's', 'a', 'gr', '##if', '##ter', 'along', 'with', 'sharp', '##ton', 'who', 'was', 'in', 'attendance', 'of', 'course', '.', 'these', 'shy', '##sters', 'det', '##est', 'trump', 'because', 'they', 'know', 'he', 's', 'the', 'real', 'deal', 'and', 'will', 'really', 'help', 'all', 'americans', '.']

In [68]:
encoded = tokenizer(article)
print(len(encoded['input_ids']))
print(encoded)

244
{'input_ids': [101, 6014, 1521, 1055, 4796, 13106, 1029, 7627, 4027, 4013, 25154, 2015, 2008, 8398, 1520, 2052, 2025, 7515, 2000, 2131, 2046, 4441, 1521, 2983, 1521, 7627, 4027, 6732, 2002, 1055, 6014, 1055, 4796, 13106, 1996, 15818, 10547, 10116, 2008, 2343, 8398, 2453, 2025, 7515, 2000, 4607, 4441, 2983, 1012, 2129, 8108, 2002, 999, 4027, 2081, 1996, 7928, 2012, 1996, 7767, 2233, 2005, 3425, 1024, 8398, 2758, 2017, 2442, 2022, 2583, 2000, 3713, 1996, 2653, 1997, 2394, 1010, 2022, 4591, 1010, 1998, 2031, 1037, 3105, 8066, 1012, 4441, 2052, 2025, 7515, 2000, 2272, 1999, 8398, 1055, 2406, 2002, 2052, 2025, 7515, 2000, 2131, 2046, 4441, 2983, 1012, 4027, 2109, 4676, 2000, 24234, 8398, 2076, 1996, 2724, 1024, 2002, 9339, 2112, 1997, 1037, 6019, 2013, 1996, 8036, 1997, 5487, 1024, 1045, 2001, 7501, 1010, 2017, 7349, 2033, 1025, 6248, 1010, 2017, 24963, 2033, 1025, 12481, 1010, 2017, 2275, 2033, 2489, 1012, 4027, 2001, 7727, 2000, 1996, 2755, 2008, 2002, 7164, 1999, 2330, 6645, 1998, 18066, 2608, 2005, 3071, 1012, 3835, 3046, 1010, 2009, 1055, 2074, 2025, 2995, 2008, 1037, 3842, 2064, 5788, 2302, 6645, 1012, 2023, 2003, 5171, 1997, 1996, 6090, 4063, 2075, 10547, 2040, 1055, 2042, 2478, 14302, 2010, 2972, 2166, 2000, 5618, 2125, 1997, 1012, 2002, 1055, 1037, 24665, 10128, 3334, 2247, 2007, 4629, 2669, 2040, 2001, 1999, 5270, 1997, 2607, 1012, 2122, 11004, 15608, 20010, 4355, 8398, 2138, 2027, 2113, 2002, 1055, 1996, 2613, 3066, 1998, 2097, 2428, 2393, 2035, 4841, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

The length of the encoded is the same as tokenized. Seems like it doesn't have an upper limit. But BERT has limited input token size - we need to address that.

In [21]:
tokenizer("hey going somewhere doing unimportant", truncation=True, max_length=3)

{'input_ids': [101, 4931, 102], 'token_type_ids': [0, 0, 0], 'attention_mask': [1, 1, 1]}

In [19]:
tokenizer.tokenize("hey going somewhere doing unimportant")

['hey', 'going', 'somewhere', 'doing', 'un', '##im', '##port', '##ant']

In [20]:
tokenizer("hey going somewhere doing unimportant")

{'input_ids': [101, 4931, 2183, 4873, 2725, 4895, 5714, 6442, 4630, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [25]:
tokenized = tokenizer("hey going somewhere doing unimportant", truncation=True, max_length=4, return_overflowing_tokens=True, stride=1)
tokenized

{'overflowing_tokens': [2183, 4873, 2725, 4895, 5714, 6442, 4630], 'num_truncated_tokens': 6, 'input_ids': [101, 4931, 2183, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [28]:
tokenized.pop('overflowing_tokens')

[2183, 4873, 2725, 4895, 5714, 6442, 4630]

### Encoding Tokens

In [30]:
tokens = tokenizer.tokenize(sentence)
tokens

['belarus',
 'leader',
 ',',
 'alexander',
 'lukas',
 '##henko',
 ',',
 'met',
 'putin',
 'on',
 'monday',
 'in',
 'soc',
 '##hi',
 '.']

In [32]:
tokenizer(tokens, is_split_into_words=True)

{'input_ids': [101, 12545, 3003, 1010, 3656, 23739, 1001, 1001, 21863, 3683, 1010, 2777, 22072, 2006, 6928, 1999, 27084, 1001, 1001, 7632, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [83]:
feature_series = pd.Series([article[0:100], article[100:200], article[200:300]], name='article')
label_series = pd.Series([1, 0, 1], name='labels')
example_data = pd.concat([feature_series, labels_series], axis=1)
example_data = example_data.sample(frac=1, random_state=43)
example_data

                                             article  labels
1  m’ Jesse Jackson thinks he s Heaven s gatekeep...       0
2  rump might not qualify to enter Jesus  Kingdom...       1
0  Heaven’s Gatekeeper? Jesse Jackson Proclaims T...       1

In [84]:
features = example_data['article']
tokenized_features = features.apply(lambda article: tokenizer.tokenize(article))
tokenized_features

1    [m, ’, jesse, jackson, thinks, he, s, heaven, ...
2    [rum, ##p, might, not, qualify, to, enter, jes...
0    [heaven, ’, s, gate, ##keeper, ?, jesse, jacks...
Name: article, dtype: object

In [93]:
original_index = tokenized_features.index
original_index

Index([1, 2, 0], dtype='int64')

In [94]:
encoded = tokenizer(tokenized_features.tolist(), is_split_into_words=True, truncation=True, max_length=5)
encoded

{'input_ids': [[101, 1049, 1521, 7627, 102], [101, 19379, 1001, 1001, 102], [101, 6014, 1521, 1055, 102]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]}

In [95]:
type(encoded)

transformers.tokenization_utils_base.BatchEncoding

In [96]:
encoded_df = pd.DataFrame(data=encoded.data, index=original_index)
encoded_df

                       input_ids   token_type_ids   attention_mask
1   [101, 1049, 1521, 7627, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]
2  [101, 19379, 1001, 1001, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]
0   [101, 6014, 1521, 1055, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]

In [97]:
data_df = pd.concat([encoded_df, labels_series], axis=1)
data_df

                       input_ids   token_type_ids   attention_mask  labels
1   [101, 1049, 1521, 7627, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]       0
2  [101, 19379, 1001, 1001, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]       1
0   [101, 6014, 1521, 1055, 102]  [0, 0, 0, 0, 0]  [1, 1, 1, 1, 1]       1

In [ ]:
hf_datasets.Dataset.from_pandas(encoded_df)